### ISSUE TITLE
Special tile position tracking

### ISSUE THREAD

**Issue by EvidentlyCube** [EvidentlyCube/chronic-temporal#69]
Right now Exit tile handling just iterates through every position in the level and checks if it's occupied both by an exit tile and a protagonist. It feels like an inelegant solution, so here is a proposed alternative:
 - [ ] Add an array of exits in a level
 - [ ] Add a new class `LevelPlotter` that'll be responsible for modifying a level
 - [ ] Make all level tile changes that happen in the editor at the moment go through the plotter
 - [ ] Make it so that `LevelPlotter` drawig methods updates the array of exits in the level as needed
 - [ ] Add a new method to level `initialize` that'll initialize the array of level exits - it should be called on clone and in level deserialization

Some references:
 * [DROD updates special tile caches on tile change](https://github.com/EvidentlyCube/drod/blob/742a99f7f1d650710e25385ddd123351e241919d/DRODLib/DbRooms.cpp#L10694)
 * [DROD initializes the tile cache on a method call](https://github.com/EvidentlyCube/drod/blob/742a99f7f1d650710e25385ddd123351e241919d/DRODLib/DbRooms.cpp#L11919)
